function createDRISHTIDistrictSimulation

model = 'DRISHTI_District_Telemedicine_Simulation';

if bdIsLoaded(model)
    close_system(model,0);
end

if isfile([model '.slx'])
    delete([model '.slx']);
end

new_system(model);
open_system(model);

set_param(model,'Solver','FixedStepDiscrete');
set_param(model,'FixedStep','1');
set_param(model,'StopTime','2400');
set_param(model,'SaveOutput','on');
set_param(model,'ReturnWorkspaceOutputs','on');

%% ---------------- INPUT PARAMETERS ----------------

% District workload
patientsPerYear = 100000;
operatingDays = 300;
hoursPerDay = 8;

% Acquisition
patientsPerHour = patientsPerYear/(operatingDays*hoursPerDay);

% Image/network assumptions
imageSizeMB = 2;
bandwidthMbps = 10;

% AI processing
aiUnits = 1;
aiProcessingSeconds = 2.4;

% Referable fraction
referableRate = 0.20;

% Human review
reviewers = 2;
reviewSeconds = 60;

%% ---------------- BASE WORKSPACE ----------------

assignin('base','DRISHTI_patientsPerYear',patientsPerYear);
assignin('base','DRISHTI_operatingDays',operatingDays);
assignin('base','DRISHTI_hoursPerDay',hoursPerDay);
assignin('base','DRISHTI_patientsPerHour',patientsPerHour);
assignin('base','DRISHTI_imageSizeMB',imageSizeMB);
assignin('base','DRISHTI_bandwidthMbps',bandwidthMbps);
assignin('base','DRISHTI_aiUnits',aiUnits);
assignin('base','DRISHTI_aiProcessingSeconds',aiProcessingSeconds);
assignin('base','DRISHTI_referableRate',referableRate);
assignin('base','DRISHTI_reviewers',reviewers);
assignin('base','DRISHTI_reviewSeconds',reviewSeconds);

%% ---------------- INPUT BLOCKS ----------------

inputs = {
    'Patients_Per_Hour','DRISHTI_patientsPerHour'
    'Image_Size_MB','DRISHTI_imageSizeMB'
    'Bandwidth_Mbps','DRISHTI_bandwidthMbps'
    'AI_Units','DRISHTI_aiUnits'
    'AI_Time_sec','DRISHTI_aiProcessingSeconds'
    'Referable_Rate','DRISHTI_referableRate'
    'Reviewers','DRISHTI_reviewers'
    'Review_Time_sec','DRISHTI_reviewSeconds'
    };

y = 70;

for i = 1:size(inputs,1)

    name = inputs{i,1};
    variable = inputs{i,2};

    block = [model '/' name];

    add_block('simulink/Sources/Constant',block,...
        'Value',variable,...
        'Position',[40 y 180 y+30]);

    y = y + 55;
end

%% ---------------- MAIN SIMULATION FUNCTION ----------------

mainBlock = [model '/District_Capacity_Model'];

add_block('simulink/User-Defined Functions/MATLAB Function',...
    mainBlock,...
    'Position',[330 180 600 470]);

code = [
"function [netQueue,aiQueue,reviewQueue,processed,reviewed,bottleneck] = districtModel(" ...
"patients,imageMB,bwMbps,aiUnits,aiSec,refRate,reviewers,reviewSec)" newline ...
"% District-level telemedicine capacity model" newline ...
"persistent nq aq rq" newline ...
"if isempty(nq)" newline ...
"    nq=0; aq=0; rq=0;" newline ...
"end" newline ...
"" newline ...
"% Convert bandwidth to images/hour" newline ...
"networkCapacity = (bwMbps*3600)/(8*imageMB);" newline ...
"" newline ...
"% AI processing capacity/hour" newline ...
"aiCapacity = aiUnits*3600/aiSec;" newline ...
"" newline ...
"% Ophthalmologist review capacity/hour" newline ...
"reviewCapacity = reviewers*3600/reviewSec;" newline ...
"" newline ...
"% Image acquisition enters network queue" newline ...
"nq = nq + patients;" newline ...
"" newline ...
"% Network transmits images" newline ...
"networkProcessed = min(nq,networkCapacity);" newline ...
"nq = nq-networkProcessed;" newline ...
"" newline ...
"% AI queue receives transmitted images" newline ...
"aq = aq+networkProcessed;" newline ...
"" newline ...
"% AI processes images" newline ...
"processed = min(aq,aiCapacity);" newline ...
"aq = aq-processed;" newline ...
"" newline ...
"% Referable cases enter review queue" newline ...
"rq = rq + processed*refRate;" newline ...
"" newline ...
"% Human review" newline ...
"reviewed = min(rq,reviewCapacity);" newline ...
"rq = rq-reviewed;" newline ...
"" newline ...
"% Identify bottleneck" newline ...
"if nq > aq && nq > rq && nq > 0" newline ...
"    bottleneck=1;" newline ...
"elseif aq > rq && aq > 0" newline ...
"    bottleneck=2;" newline ...
"elseif rq > 0" newline ...
"    bottleneck=3;" newline ...
"else" newline ...
"    bottleneck=0;" newline ...
"end" newline ...
"" newline ...
"netQueue=nq;" newline ...
"aiQueue=aq;" newline ...
"reviewQueue=rq;" newline ...
"end"
];

set_param(mainBlock,'Script',code);

%% ---------------- OUTPUT BLOCKS ----------------

outputs = {
    'Network_Queue',1
    'AI_Queue',2
    'Review_Queue',3
    'Processed_Per_Hour',4
    'Reviewed_Per_Hour',5
    'Bottleneck',6
    };

x = 720;
y = 80;

for i = 1:size(outputs,1)

    name = outputs{i,1};
    port = outputs{i,2};

    block = [model '/' name];

    add_block('simulink/Sinks/Display',block,...
        'Position',[x y x+130 y+35]);

    add_line(model,...
        ['District_Capacity_Model/' num2str(port)],...
        [name '/1'],...
        'autorouting','on');

    y = y + 65;
end

%% ---------------- INPUT CONNECTIONS ----------------

for i = 1:size(inputs,1)

    add_line(model,...
        [inputs{i,1} '/1'],...
        ['District_Capacity_Model/' num2str(i)],...
        'autorouting','on');

end

%% ---------------- TO WORKSPACE OUTPUTS ----------------

names = {
    'NetworkQueue_Result',1
    'AIQueue_Result',2
    'ReviewQueue_Result',3
    'Processed_Result',4
    'Reviewed_Result',5
    'Bottleneck_Result',6
    };

y = 520;

for i = 1:size(names,1)

    block = [model '/' names{i,1}];

    add_block('simulink/Sinks/To Workspace',block,...
        'VariableName',names{i,1},...
        'SaveFormat','Array',...
        'Position',[720 y 900 y+30]);

    add_line(model,...
        ['District_Capacity_Model/' num2str(names{i,2})],...
        [names{i,1} '/1'],...
        'autorouting','on');

    y = y + 40;

end

%% ---------------- ANNOTATION ----------------

annotation = sprintf([ ...
    'DRISHTI DISTRICT TELEMEDICINE CAPACITY MODEL\\n' ...
    'Annual workload: 100,000 patients\\n' ...
    'Simulation horizon: 300 days × 8 hours/day\\n' ...
    'Time step: 1 hour\\n' ...
    'Bottlenecks: Network / AI / Human Review' ]);

add_block('simulink/Model-Wide Utilities/Model Info',...
    [model '/Model_Info'],...
    'Position',[40 600 400 700]);

%% ---------------- SAVE ----------------

save_system(model,...
    fullfile(pwd,'simulink',[model '.slx']));

open_system(model);

fprintf('\nDRISHTI district simulation created successfully.\n');
fprintf('Model: simulink/%s.slx\n',model);

end