function createDRISHTISimulink()
% ============================================================
% DRISHTI - Diabetic Retinopathy Intelligent Screening
% and Health Technology Initiative
%
% Smart India Hackathon 2026
%
% Purpose:
%   System-level Simulink model for:
%       Fundus screening
%       Quality assessment
%       Preprocessing
%       AI inference
%       DR grading
%       Referable DR decision
%       Explainability/report
%       Human review
%       Timing and throughput
%
% IMPORTANT:
%   The actual trained AI remains in MATLAB.
%   This Simulink model represents the system workflow,
%   decision logic, timing and deployment behavior.
%
% ============================================================

clc;

%% ------------------------------------------------------------
% Project paths
% -------------------------------------------------------------

projectRoot = 'C:\Users\SHIVANYA SALES\Desktop\DR tejas\SIH_DR_Screening';
simulinkDir = fullfile(projectRoot,'simulink');

if ~exist(simulinkDir,'dir')
    mkdir(simulinkDir);
end

modelName = 'DRISHTI_Screening_System';
modelFile = fullfile(simulinkDir,[modelName '.slx']);

%% ------------------------------------------------------------
% Close old model if already loaded
% -------------------------------------------------------------

if bdIsLoaded(modelName)
    close_system(modelName,0);
end

if exist(modelFile,'file')
    delete(modelFile);
end

%% ------------------------------------------------------------
% Create new Simulink model
% -------------------------------------------------------------

new_system(modelName);
open_system(modelName);

%% ------------------------------------------------------------
% Model configuration
% -------------------------------------------------------------

set_param(modelName,...
    'StopTime','1',...
    'Solver','FixedStepAuto',...
    'SaveOutput','off',...
    'SignalLogging','off');

%% ------------------------------------------------------------
% Default scenario values
%
% These represent one screening case.
%
% qualityScore:
%   0.0 - 1.0
%
% gradeInput:
%   ICDR grade 0-4
%
% modelScore:
%   maximum model probability
%
% IMPORTANT:
%   These are simulation inputs, not new clinical results.
% -------------------------------------------------------------

qualityScore = 0.85;
gradeInput  = 2;
modelScore  = 0.5395;

assignin('base','DRISHTI_qualityScore',qualityScore);
assignin('base','DRISHTI_gradeInput',gradeInput);
assignin('base','DRISHTI_modelScore',modelScore);

%% ------------------------------------------------------------
% Timing assumptions
%
% These are engineering assumptions for the Simulink
% deployment model and are NOT measured clinical performance.
% -------------------------------------------------------------

qualityTime      = 0.20;
preprocessTime   = 0.30;
inferenceTime    = 1.00;
explainTime      = 0.50;
reportTime       = 0.20;
humanReviewTime  = 30.0;

assignin('base','DRISHTI_qualityTime',qualityTime);
assignin('base','DRISHTI_preprocessTime',preprocessTime);
assignin('base','DRISHTI_inferenceTime',inferenceTime);
assignin('base','DRISHTI_explainTime',explainTime);
assignin('base','DRISHTI_reportTime',reportTime);
assignin('base','DRISHTI_humanReviewTime',humanReviewTime);

%% ============================================================
% BLOCKS
% =============================================================

%% ------------------------------------------------------------
% INPUT BLOCKS
% -------------------------------------------------------------

add_block( ...
    'simulink/Sources/Constant',...
    [modelName '/Quality_Score'],...
    'Value','DRISHTI_qualityScore',...
    'Position',[40 100 150 130]);

add_block( ...
    'simulink/Sources/Constant',...
    [modelName '/DR_Grade_Input'],...
    'Value','DRISHTI_gradeInput',...
    'Position',[40 230 150 260]);

add_block( ...
    'simulink/Sources/Constant',...
    [modelName '/Model_Score'],...
    'Value','DRISHTI_modelScore',...
    'Position',[40 300 150 330]);

%% ------------------------------------------------------------
% QUALITY ASSESSMENT
% -------------------------------------------------------------

add_block( ...
    'simulink/User-Defined Functions/MATLAB Function',...
    [modelName '/Quality_Assessment'],...
    'Position',[220 80 390 160]);

qualityBlock = find( ...
    get_param(modelName,'Object'),...
    '-isa','Stateflow.EMChart',...
    'Path',[modelName '/Quality_Assessment']);

qualityBlock.Script = sprintf([ ...
    'function [accepted,borderline,statusCode] = qualityCheck(q)' newline ...
    '%% Quality assessment logic' newline ...
    '%% 0 = REJECT, 1 = BORDERLINE, 2 = ACCEPT' newline ...
    'if q < 0.40' newline ...
    '    accepted = false;' newline ...
    '    borderline = false;' newline ...
    '    statusCode = 0;' newline ...
    'elseif q < 0.65' newline ...
    '    accepted = true;' newline ...
    '    borderline = true;' newline ...
    '    statusCode = 1;' newline ...
    'else' newline ...
    '    accepted = true;' newline ...
    '    borderline = false;' newline ...
    '    statusCode = 2;' newline ...
    'end' newline ...
    'end']);

%% ------------------------------------------------------------
% PREPROCESSING
% -------------------------------------------------------------

add_block( ...
    'simulink/User-Defined Functions/MATLAB Function',...
    [modelName '/Preprocessing'],...
    'Position',[450 80 620 160]);

prepBlock = find( ...
    get_param(modelName,'Object'),...
    '-isa','Stateflow.EMChart',...
    'Path',[modelName '/Preprocessing']);

prepBlock.Script = sprintf([ ...
    'function [ready,enhanced] = preprocess(accepted,borderline)' newline ...
    '%% Preprocessing decision' newline ...
    'if ~accepted' newline ...
    '    ready = false;' newline ...
    '    enhanced = false;' newline ...
    'elseif borderline' newline ...
    '    ready = true;' newline ...
    '    enhanced = true;' newline ...
    'else' newline ...
    '    ready = true;' newline ...
    '    enhanced = false;' newline ...
    'end' newline ...
    'end']);

%% ------------------------------------------------------------
% AI INFERENCE
% -------------------------------------------------------------

add_block( ...
    'simulink/User-Defined Functions/MATLAB Function',...
    [modelName '/AI_Inference'],...
    'Position',[680 80 850 160]);

aiBlock = find( ...
    get_param(modelName,'Object'),...
    '-isa','Stateflow.EMChart',...
    'Path',[modelName '/AI_Inference']);

aiBlock.Script = sprintf([ ...
    'function [grade,score] = inference(ready,gradeInput,modelScore)' newline ...
    '%% AI inference interface' newline ...
    '%% Actual ResNet inference remains in MATLAB.' newline ...
    'if ready' newline ...
    '    grade = gradeInput;' newline ...
    '    score = modelScore;' newline ...
    'else' newline ...
    '    grade = -1;' newline ...
    '    score = 0;' newline ...
    'end' newline ...
    'end']);

%% ------------------------------------------------------------
% REFERABLE DR DECISION
% -------------------------------------------------------------

add_block( ...
    'simulink/User-Defined Functions/MATLAB Function',...
    [modelName '/Referral_Decision'],...
    'Position',[910 80 1080 160]);

refBlock = find( ...
    get_param(modelName,'Object'),...
    '-isa','Stateflow.EMChart',...
    'Path',[modelName '/Referral_Decision']);

refBlock.Script = sprintf([ ...
    'function [referable,decisionCode] = referralDecision(grade)' newline ...
    '%% ICDR grade >= 2 is treated as referable' newline ...
    'if grade < 0' newline ...
    '    referable = false;' newline ...
    '    decisionCode = 0;' newline ...
    'elseif grade >= 2' newline ...
    '    referable = true;' newline ...
    '    decisionCode = 2;' newline ...
    'else' newline ...
    '    referable = false;' newline ...
    '    decisionCode = 1;' newline ...
    'end' newline ...
    'end']);

%% ------------------------------------------------------------
% EXPLAINABLE REPORT
% -------------------------------------------------------------

add_block( ...
    'simulink/User-Defined Functions/MATLAB Function',...
    [modelName '/Explainable_Report'],...
    'Position',[1110 80 1290 180]);

reportBlock = find( ...
    get_param(modelName,'Object'),...
    '-isa','Stateflow.EMChart',...
    'Path',[modelName '/Explainable_Report']);

reportBlock.Script = sprintf([ ...
    'function [reportCode,humanReview] = report(statusCode,grade,score,referable)' newline ...
    '%% Explainable report state' newline ...
    '%% 0 = rejected image' newline ...
    '%% 1 = non-referable' newline ...
    '%% 2 = referable' newline ...
    'if statusCode == 0' newline ...
    '    reportCode = 0;' newline ...
    '    humanReview = false;' newline ...
    'elseif grade >= 2 && referable' newline ...
    '    reportCode = 2;' newline ...
    '    humanReview = true;' newline ...
    'else' newline ...
    '    reportCode = 1;' newline ...
    '    humanReview = false;' newline ...
    'end' newline ...
    'end']);

%% ------------------------------------------------------------
% SYSTEM TIMING MODEL
% -------------------------------------------------------------

add_block( ...
    'simulink/User-Defined Functions/MATLAB Function',...
    [modelName '/System_Timing'],...
    'Position',[1110 260 1290 370]);

timingBlock = find( ...
    get_param(modelName,'Object'),...
    '-isa','Stateflow.EMChart',...
    'Path',[modelName '/System_Timing']);

timingBlock.Script = sprintf([ ...
    'function [totalTime,throughput,reviewTime] = timingModel(' ...
    'accepted,borderline,referable)' newline ...
    '%% System timing model' newline ...
    'qualityTime = DRISHTI_qualityTime;' newline ...
    'preprocessTime = DRISHTI_preprocessTime;' newline ...
    'inferenceTime = DRISHTI_inferenceTime;' newline ...
    'explainTime = DRISHTI_explainTime;' newline ...
    'reportTime = DRISHTI_reportTime;' newline ...
    'humanTime = DRISHTI_humanReviewTime;' newline ...
    'if ~accepted' newline ...
    '    totalTime = qualityTime;' newline ...
    '    reviewTime = 0;' newline ...
    'else' newline ...
    '    totalTime = qualityTime + preprocessTime + ...' newline ...
    '        inferenceTime + explainTime + reportTime;' newline ...
    '    if borderline' newline ...
    '        totalTime = totalTime + 0.20;' newline ...
    '    end' newline ...
    '    if referable' newline ...
    '        reviewTime = humanTime;' newline ...
    '    else' newline ...
    '        reviewTime = 0;' newline ...
    '    end' newline ...
    'end' newline ...
    'throughput = 60/totalTime;' newline ...
    'end']);

%% ------------------------------------------------------------
% OUTPUT DISPLAYS
% -------------------------------------------------------------

add_block( ...
    'simulink/Sinks/Display',...
    [modelName '/Grade_Display'],...
    'Position',[1320 80 1430 120]);

add_block( ...
    'simulink/Sinks/Display',...
    [modelName '/Referable_Display'],...
    'Position',[1320 140 1430 180]);

add_block( ...
    'simulink/Sinks/Display',...
    [modelName '/Total_Time_Display'],...
    'Position',[1320 270 1430 310]);

add_block( ...
    'simulink/Sinks/Display',...
    [modelName '/Throughput_Display'],...
    'Position',[1320 330 1430 370]);

add_block( ...
    'simulink/Sinks/Display',...
    [modelName '/Human_Review_Display'],...
    'Position',[1320 390 1430 430]);

%% ------------------------------------------------------------
% TO WORKSPACE OUTPUTS
% -------------------------------------------------------------

add_block( ...
    'simulink/Sinks/To Workspace',...
    [modelName '/Grade_ToWorkspace'],...
    'VariableName','DRISHTI_grade_result',...
    'SaveFormat','Timeseries',...
    'Position',[1450 80 1590 120]);

add_block( ...
    'simulink/Sinks/To Workspace',...
    [modelName '/Referable_ToWorkspace'],...
    'VariableName','DRISHTI_referable_result',...
    'SaveFormat','Timeseries',...
    'Position',[1450 140 1590 180]);

add_block( ...
    'simulink/Sinks/To Workspace',...
    [modelName '/Timing_ToWorkspace'],...
    'VariableName','DRISHTI_timing_result',...
    'SaveFormat','Timeseries',...
    'Position',[1450 270 1590 310]);

%% ============================================================
% CONNECTIONS
% =============================================================

% Quality score -> quality assessment
Simulink.connectBlocks( ...
    [modelName '/Quality_Score'],...
    [modelName '/Quality_Assessment']);

% Quality accepted/borderline -> preprocessing
Simulink.connectBlocks( ...
    [modelName '/Quality_Assessment'],...
    [modelName '/Preprocessing']);

% Preprocessing -> AI
Simulink.connectBlocks( ...
    [modelName '/Preprocessing'],...
    [modelName '/AI_Inference']);

% Grade and model score inputs -> AI
Simulink.connectBlocks( ...
    [modelName '/DR_Grade_Input'],...
    [modelName '/AI_Inference']);

Simulink.connectBlocks( ...
    [modelName '/Model_Score'],...
    [modelName '/AI_Inference']);

% AI -> referral
Simulink.connectBlocks( ...
    [modelName '/AI_Inference'],...
    [modelName '/Referral_Decision']);

% Quality status + AI + referral -> report
Simulink.connectBlocks( ...
    [modelName '/Quality_Assessment'],...
    [modelName '/Explainable_Report']);

Simulink.connectBlocks( ...
    [modelName '/AI_Inference'],...
    [modelName '/Explainable_Report']);

Simulink.connectBlocks( ...
    [modelName '/Referral_Decision'],...
    [modelName '/Explainable_Report']);

% Timing inputs
Simulink.connectBlocks( ...
    [modelName '/Quality_Assessment'],...
    [modelName '/System_Timing']);

Simulink.connectBlocks( ...
    [modelName '/Preprocessing'],...
    [modelName '/System_Timing']);

Simulink.connectBlocks( ...
    [modelName '/Referral_Decision'],...
    [modelName '/System_Timing']);

% Outputs
Simulink.connectBlocks( ...
    [modelName '/AI_Inference/1'],...
    [modelName '/Grade_Display']);

Simulink.connectBlocks( ...
    [modelName '/Referral_Decision/1'],...
    [modelName '/Referable_Display']);

Simulink.connectBlocks( ...
    [modelName '/AI_Inference/1'],...
    [modelName '/Grade_ToWorkspace']);

Simulink.connectBlocks( ...
    [modelName '/Referral_Decision/1'],...
    [modelName '/Referable_ToWorkspace']);

Simulink.connectBlocks( ...
    [modelName '/System_Timing/1'],...
    [modelName '/Total_Time_Display']);

Simulink.connectBlocks( ...
    [modelName '/System_Timing/2'],...
    [modelName '/Throughput_Display']);

Simulink.connectBlocks( ...
    [modelName '/System_Timing/3'],...
    [modelName '/Human_Review_Display']);

Simulink.connectBlocks( ...
    [modelName '/System_Timing'],...
    [modelName '/Timing_ToWorkspace']);

%% ------------------------------------------------------------
% Add annotations
% -------------------------------------------------------------

add_block( ...
    'simulink/Model-Wide Utilities/Model Info',...
    [modelName '/Model_Info'],...
    'Position',[40 400 200 460]);

%% ------------------------------------------------------------
% Automatic layout
% -------------------------------------------------------------

try
    Simulink.BlockDiagram.arrangeSystem(modelName);
catch
    % Keep manually assigned positions if automatic layout
    % is unavailable.
end

%% ------------------------------------------------------------
% Add model description
% -------------------------------------------------------------

set_param(modelName,...
    'Description',...
    ['DRISHTI - Explainable AI for Diabetic Retinopathy Screening' newline ...
     'System-level MATLAB/Simulink model for rural screening workflow.' newline ...
     'MATLAB performs AI algorithms; Simulink models workflow, decisions,' newline ...
     'timing, throughput and human-in-the-loop behavior.']);

%% ------------------------------------------------------------
% Save checkpoint
% -------------------------------------------------------------

save_system(modelName,modelFile);

fprintf('\n');
fprintf('====================================================\n');
fprintf('DRISHTI Simulink model created successfully.\n');
fprintf('====================================================\n');
fprintf('Model:\n%s\n\n',modelFile);

fprintf('Simulation inputs:\n');
fprintf('  Quality score : %.3f\n',qualityScore);
fprintf('  DR grade      : %d\n',gradeInput);
fprintf('  Model score   : %.4f\n\n',modelScore);

fprintf('Timing assumptions:\n');
fprintf('  Quality       : %.2f s\n',qualityTime);
fprintf('  Preprocessing : %.2f s\n',preprocessTime);
fprintf('  Inference     : %.2f s\n',inferenceTime);
fprintf('  Explainability: %.2f s\n',explainTime);
fprintf('  Report        : %.2f s\n',reportTime);
fprintf('  Human review  : %.2f s\n',humanReviewTime);

fprintf('\nOpen the model with:\n');
fprintf('  open_system(''%s'')\n',modelName);

fprintf('====================================================\n');

end